# Generated by Django 4.0.4 on 2022-05-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatDogLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('label', models.CharField(choices=[('cat', "It's a Citty."), ('dog', "It's a Doggo.")], max_length=30, verbose_name='Image Class/Label')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Prediction Confidence')),
            ],
        ),
    ]
